const AllData = [
    {
        id:1,
        img:"https://img-c.udemycdn.com/course/240x135/8324_fa84_13.jpg",
        heading:"Powerful Business Writing: How to Write Concisely",           
        author:"Caroline McDevitt",
        des:"A concise business writing course for punchy, professional and powerful writing – at work, at university, on your blog",
        rating:"4.7",
        price:499,
        category:"Business",
        subcat:"Communication"
    },
    {
        id:2,
        img:"https://img-c.udemycdn.com/course/240x135/1355610_375a_5.jpg",
        heading:"Communication Fundamentals: How To Communicate Better",           
        author:"Life Progression Project, Lorraine Wiseman",
        des:"Become an Effective Communicator And Learn How to Get Your Message Across By Learning Communication Fundamentals",
        rating:"4.5",
        price:699,
        category:"Business",
        subcat:"Communication"
    },
    {
        id:3,
        img:"https://img-c.udemycdn.com/course/240x135/946654_dbfb_3.jpg",
        heading:"Write Better Emails: Tactics for Smarter Team Communication",           
        author:"Hassan Osman",
        des:"How to improve your email writing skills to save time & improve communication with your team; easy business writing tips",
        rating:"4.6",
        price:699,
        category:"Business",
        subcat:"Communication"
    },
    {
        id:4,
        img:"https://img-c.udemycdn.com/course/240x135/552372_1adb.jpg",
        heading:"Email Etiquette: Write More Effective Emails At Work",           
        author:"Clare Lynch",
        des:"How to write emails that get results. How to write emails that build better working relationships.",
        rating:"4.5",
        price:699,
        category:"Business",
        subcat:"Communication"
    },
    {
        id:5,
        img:"https://img-c.udemycdn.com/course/240x135/1366348_9ff2_5.jpg",
        heading:"Cross-Cultural Communication: How To Flex Your Style",           
        author:"Life Progression Project, Lorraine Wiseman",
        des:"Cross-Cultural Communication: Using Language Appropriately, Expressions, Gestures & Cues, Cultural Profiles & more!",
        rating:"4.4",
        price:699,
        category:"Business",
        subcat:"Communication"
    },
    {
        id:6,
        img:"https://img-c.udemycdn.com/course/480x270/613808_3c1c_6.jpg",
        heading:"Leadership: Practical Leadership Skills",           
        author:"Chris Croft",
        des:"Master leadership skills and leadership techniques with this highly practical advice and training",
        rating:"4.6",
        price:699,
        category:"Business",
        subcat:"Managements"
    },
    {
        id:7,
        img:"https://img-c.udemycdn.com/course/480x270/673654_d677_7.jpg",
        heading:"Become a Product Manager | Learn the Skills & Get the Job",           
        author:"Cole Mercer, Evan Kimbrell",
        des:"The most complete course available on Product Management. 13+ hours of videos, activities, interviews, & more",
        rating:"4.5",
        price:699,
        category:"Business",
        subcat:"Managements"
    },
    {
        id:8,
        img:"https://img-c.udemycdn.com/course/480x270/110240_9cb3_8.jpg",
        heading:"How to Manage & Influence Your Virtual Team",           
        author:"Hassan Osman",
        des:"Learn step-by-step tips that help you get things done with your virtual team by increasing trust and accountability",
        rating:"4.4",
        price:699,
        category:"Business",
        subcat:"Managements"
    },
    {
        id:9,
        img:"https://img-c.udemycdn.com/course/480x270/1355158_33a4_2.jpg",
        heading:"Creativity, Design Thinking, and Innovation for Business",           
        author:"Joeel & Natalie Rivera, Transformation Services",
        des:"Creativity that Create an Innovative Corporate Culture Using Design Thinking & Problem Solving for the Workplace",
        rating:"4.4",
        price:699,
        category:"Business",
        subcat:"Managements"
    },
    {
        id:10,
        img:"https://img-c.udemycdn.com/course/480x270/1362218_70a6_8.jpg",
        heading:"Leadership: How to Influence, Inspire and Impact as a Leader",           
        author:"Life Progression Project, Lorraine Wiseman",
        des:"Leading Others Using Effective Leadership Methods That'll Get You Results! Influence, Inspire & Impact as a Leader",
        rating:"4.5",
        price:699,
        category:"Business",
        subcat:"Managements"
    },
    {
        id:11,
        img:"https://img-c.udemycdn.com/course/480x270/2409722_af72.jpg",
        heading:"Design Thinking for Beginners: Develop Innovative Ideas",           
        author:"Laura Pickel",
        des:"Apply the five-step design thinking process to identify and creatively solve problems using a human-centered approach.",
        rating:"4.4",
        price:699,
        category:"Business",
        subcat:"Business Strategy"
    },
    {
        id:12,
        img:"https://img-c.udemycdn.com/course/480x270/1361726_508a_2.jpg",
        heading:"Security Awareness Training, Internet Security for Employees",           
        author:"Roy Davis",
        des:"Basic security awareness guide on Internet security and privacy to help keep you, your home, and your employer safe.",
        rating:"4.6",
        price:699,
        category:"Business",
        subcat:"Business Strategy"
    },
    {
        id:13,
        img:"https://img-c.udemycdn.com/course/480x270/2266662_75e0.jpg",
        heading:"CHANGE MANAGEMENT FOR ORGANIZATIONS: Drive Strategic Results",           
        author:"Vicki Hart",
        des:"Lead change using leadership alignment, stakeholder engagement, culture assessment, communication, and training.",
        rating:"4.4",
        price:699,
        category:"Business",
        subcat:"Business Strategy"
    },
    {
        id:14,
        img:"https://img-c.udemycdn.com/course/480x270/510548_8892_2.jpg",
        heading:"Defining a Digital Transformation Roadmap",           
        author:"Mike Connor",
        des:"Learn how to define and implement a phased digital transformation program to establish your company as a digital leader.",
        rating:"4.5",
        price:699,
        category:"Business",
        subcat:"Business Strategy"
    },
    {
        id:15,
        img:"https://img-c.udemycdn.com/course/480x270/1030316_c58a_6.jpg",
        heading:"Business Model Innovation: Differentiate & Grow Your Company",           
        author:"Paul Nekh. | Business | Innovation | Video, Olena T. (FR)",
        des:"Use these simple Innovation Strategies for your Business Model to Accelerate the Growth of your Business",
        rating:"4.6",
        price:699,
        category:"Business",
        subcat:"Business Strategy"
    },
    {
        id:16,
        img:"https://img-c.udemycdn.com/course/480x270/1340842_f36d_8.jpg",
        heading:"Robotic Process Automation - RPA Overview",           
        author:"Bryan Lamb",
        des:"Get the RPA big picture from a top-ranked, 4-time UiPath MVP!",
        rating:"4.5",
        price:699,
        category:"Business",
        subcat:"Operations"
    },
    {
        id:17,
        img:"https://img-c.udemycdn.com/course/480x270/1399954_9e5b_25.jpg",
        heading:"Six Sigma: Certified Lean Six Sigma Green Belt | Accredited",           
        author:"Six Sigma Academy Amsterdam",
        des:"Accredited Lean Six Sigma Green Belt training and certification | 100k+ Lean Six Sigma certifications | Earn Credits",
        rating:"4.6",
        price:699,
        category:"Business",
        subcat:"Operations"
    },
    {
        id:18,
        img:"https://img-c.udemycdn.com/course/480x270/120872_80cf_16.jpg",
        heading:"Customer Success | How to Understand Your Customers",           
        author:"Chuck Wall",
        des:"Turn Listening into Fantastic Results",
        rating:"4.5",
        price:699,
        category:"Business",
        subcat:"Operations"
    },
    {
        id:19,
        img:"https://img-c.udemycdn.com/course/480x270/1039210_5146_28.jpg",
        heading:"Lean Management Certification | Lean Expert | Accredited",           
        author:"Six Sigma Academy Amsterdam",
        des:"Lean Management Certification, Lean And Six Sigma For All Sectors, Including Manufacturing, 150k Certified, Earn Credits",
        rating:"4.7",
        price:699,
        category:"Business",
        subcat:"Operations"
    },
    {
        id:20,
        img:"https://img-c.udemycdn.com/course/480x270/2041462_72fc_3.jpg",
        heading:"Robotic Process Automation: RPA Overview + Build a Robot",           
        author:"Tor-Inge Flaa",
        des:"Learn the key elements of RPA and build your first software robot in less than half a workday!",
        rating:"4.4",
        price:699,
        category:"Business",
        subcat:"Operations"
    },
    {
        id:21,
        img:"https://img-c.udemycdn.com/course/480x270/536482_9403_5.jpg",
        heading:"Security Awareness Training",           
        author:"Michael Biocchi",
        des:"A basic guide to staying safe online and to introduce new knowledge to people about internet security and privacy.",
        rating:"4.6",
        price:699,
        category:"Business",
        subcat:"Human Resources"
    },
    {
        id:22,
        img:"https://img-c.udemycdn.com/course/480x270/2562342_3f79.jpg",
        heading:"Diversity, Equity, and Inclusion: A Beginner’s Guide",           
        author:"Ulysses Smith",
        des:"Practical strategies for developing your company's global Diversity, Equity, and Inclusion function",
        rating:"4.5",
        price:699,
        category:"Business",
        subcat:"Human Resources"
    },
    {
        id:23,
        img:"https://img-c.udemycdn.com/course/480x270/2412206_cba1_4.jpg",
        heading:"Unconscious Bias: Fuel Diversity and Become a Better You",           
        author:"Gail Miller",
        des:"Defeat unconscious bias and build diversity and inclusion into your life even if it seems impossible right now!",
        rating:"4.4",
        price:699,
        category:"Business",
        subcat:"Human Resources"
    },
    {
        id:24,
        img:"https://img-c.udemycdn.com/course/480x270/934526_b707_4.jpg",
        heading:"Developing Emotional Intelligence in Teams",           
        author:"Robin Hills",
        des:"Maximise Team Performance: Strategies for Developing Emotional Intelligence In Teams | Enhancing Relationships",
        rating:"4.5",
        price:699,
        category:"Business",
        subcat:"Human Resources"
    },
    {
        id:25,
        img:"https://img-c.udemycdn.com/course/480x270/2507704_2ff2_2.jpg",
        heading:"Diversity & Inclusion: Building a Grassroots Foundation",           
        author:"Jennifer Kim",
        des:"Practical strategies for building an organizational culture of diversity, equity, inclusion, and belonging",
        rating:"4.6",
        price:699,
        category:"Business",
        subcat:"Human Resources"
    },
    {
        id:26,
        img:"https://img-c.udemycdn.com/course/480x270/888716_4225_8.jpg",
        heading:"Introduction to Finance, Accounting, Modeling and Valuation",           
        author:"Chris Haroun | 1.4 Million Students | #1 Best Selling Business & Finance Prof",
        des:"Learn Finance & Accounting from Scratch by an Award Winning MBA Professor, Ivy Grad, worked @ Goldman & VC",
        rating:"4.5",
        price:699,
        category:"Finance & Accounting",
        subcat:"Accounting & Bookkeeping"
    },
    {
        id:27,
        img:"https://img-c.udemycdn.com/course/480x270/640100_9f85_5.jpg",
        heading:"Accounting & Financial Statement Analysis: Complete Training",           
        author:"365 Careers",
        des:"Accounting & Financial Ratio Analysis made easy. Learn important accounting skills that will get your foot in the door!",
        rating:"4.6",
        price:699,
        category:"Finance & Accounting",
        subcat:"Accounting & Bookkeeping"
    },
    {
        id:28,
        img:"https://img-c.udemycdn.com/course/480x270/48841_9110_7.jpg",
        heading:"Accounting in 60 Minutes - A Brief Introduction",           
        author:"Vincent Turner",
        des:"Learn the very basics of accounting in just about an hour.",
        rating:"4.5",
        price:699,
        category:"Finance & Accounting",
        subcat:"Accounting & Bookkeeping"
    },
    {
        id:29,
        img:"https://img-c.udemycdn.com/course/480x270/1592862_c178_2.jpg",
        heading:"SAP FICO (Financial Accounting & Management Accounting)",           
        author:"Rana W Mehmood",
        des:"The course covers both configuration and end-user processes for SAP FICO module",
        rating:"4.4",
        price:699,
        category:"Finance & Accounting",
        subcat:"Accounting & Bookkeeping"
    },
    {
        id:30,
        img:"https://img-c.udemycdn.com/course/480x270/133428_e67a_18.jpg",
        heading:"Accounting: From Beginner to Advanced!",           
        author:"Stefan Ignatovski, Ph.D.",
        des:"Learn accounting like never before. Learn easy and fast. Easy to understand Accounting. #1 accounting course online.",
        rating:"4.5",
        price:699,
        category:"Finance & Accounting",
        subcat:"Accounting & Bookkeeping"
    },
    {
        id:31,
        img:"https://img-c.udemycdn.com/course/480x270/3385322_e814_2.jpg",
        heading:"Anti-Money Laundering Concepts: AML, KYC and Compliance",           
        author:"GenMan Solutions",
        des:"(Highest number of Students Enrolled) Anti-Money Laundering(AML), AML policies, AML KYC & AML Compliance",
        rating:"4.5",
        price:699,
        category:"Finance & Accounting",
        subcat:"Compliance"
    },
    {
        id:32,
        img:"https://img-c.udemycdn.com/course/480x270/1342930_1a6d_5.jpg",
        heading:"Anti-Money Laundering and Combating Terrorism Financing",           
        author:"g-Log Consult",
        des:"AML Concepts, Customer Due Diligence Principles, Controls and Procedures",
        rating:"4.3",
        price:699,
        category:"Finance & Accounting",
        subcat:"Compliance"
    },
    {
        id:33,
        img:"https://img-c.udemycdn.com/course/480x270/3275814_85ee_4.jpg",
        heading:"The Ultimate Guide to Money Laundering and AML Compliance",           
        author:"Financial Crime Academy, Florian Haufe",
        des:"Learn the Fundamentals of Money Laundering and Gain Practical Insights into Anti Money Laundering Compliance",
        rating:"4.4",
        price:699,
        category:"Finance & Accounting",
        subcat:"Compliance"
    },
    {
        id:34,
        img:"https://img-c.udemycdn.com/course/480x270/4273070_1801_2.jpg",
        heading:"The Complete Guide To Anti Money Laundering (AML) Compliance",           
        author:"SIA Global Security",
        des:"What You Should Know about Anti Money Laundering (AML), AML Compliance, AML Policies, and Know Your Customer (KYC)",
        rating:"4.4",
        price:699,
        category:"Finance & Accounting",
        subcat:"Compliance"
    },
    {
        id:35,
        img:"https://img-c.udemycdn.com/course/480x270/968248_92cb_3.jpg",
        heading:"Anti Money Laundering & Countering of Terrorist Financing",           
        author:"COMPLYFIN DWC LLC",
        des:"From Leading Subject Matter Experts,  Compliance , AML/CFT (Consolidated Quick Learning Video)",
        rating:"4.5",
        price:699,
        category:"Finance & Accounting",
        subcat:"Compliance"
    },
    {
        id:36,
        img:"https://img-c.udemycdn.com/course/480x270/1378318_d894_6.jpg",
        heading:"Economics: Market Forces of Demand, Supply and Equilibrium",           
        author:"Evrim Kanbur",
        des:"Economics: Analyzing Demand, Supply and Market Equilibrium with real life case studies.",
        rating:"4.5",
        price:999,
        category:"Finance & Accounting",
        subcat:"Economic"
    },
    {
        id:37,
        img:"https://img-c.udemycdn.com/course/480x270/638604_c94a_4.jpg",
        heading:"(Oxford) Master Diploma : Economics (Includes Macro/Micro)",           
        author:"Chris Sivewright",
        des:"NINETY HOURS : Micro/Macro/Global/Business/Behavioural Economics",
        rating:"4.5",
        price:529,
        category:"Finance & Accounting",
        subcat:"Economic"
    },
    {
        id:38,
        img:"https://img-c.udemycdn.com/course/480x270/767836_a4d6_2.jpg",
        heading:"Understanding Macroeconomics for University and Business",           
        author:"Saifedean Ammous",
        des:"Explaining the economics of fiscal policy, money creation, and monetary policy",
        rating:"4.7",
        price:1299,
        category:"Finance & Accounting",
        subcat:"Economic"
    },
    {
        id:39,
        img:"https://img-c.udemycdn.com/course/480x270/3707394_29fc_2.jpg",
        heading:"Macroeconomics: A Comprehensive Economics Course",           
        author:"Brad Cartwright",
        des:"A Course Designed to Give You a Better Understanding of the World Around You--Perfect for University and Adult Learners!",
        rating:"4.8",
        price:529,
        category:"Finance & Accounting",
        subcat:"Economic"
    },
    {
        id:40,
        img:"https://img-c.udemycdn.com/course/480x270/2812245_7db7.jpg",
        heading:"The Macroeconomics Course",           
        author:"365 Careers",
        des:"Aggregate Output and Economic Growth. Business Cycles. Monetary and Fiscal Policy. International Trade and Capital Flows",
        rating:"4.8",
        price:529,
        category:"Finance & Accounting",
        subcat:"Economic"
    },
    {
        id:41,
        img:"https://img-c.udemycdn.com/course/480x270/965832_212f_4.jpg",
        heading:"The Complete Investment Banking Course 2023",           
        author:"365 Careers",
        des:"The #1 Course to Land a Job in Investment Banking. IPOs, Bonds, M&A, Trading, LBOs, Valuation: Everything  is included!",
        rating:"4.5",
        price:529,
        category:"Finance & Accounting",
        subcat:"Finance"
    },
    {
        id:42,
        img:"https://img-c.udemycdn.com/course/480x270/595258_5192_3.jpg",
        heading:"Finance for Non-Finance: Learn Quick and Easy",           
        author:"Anthony Jameson",
        des:"Obtain Suplemental Skills to Get a Raise, Better Job or Improve Your Own Business",
        rating:"4.5",
        price:529,
        category:"Finance & Accounting",
        subcat:"Finance"
    },
    {
        id:43,
        img:"https://img-c.udemycdn.com/course/480x270/1326708_82ae_4.jpg",
        heading:"MBA ASAP Corporate Finance Fundamentals for Career Success",           
        author:"John Cousins",
        des:"Concepts & Tools of Financial Analysis, Valuation, Investing, Money Management, and Decision Making. DCF,NPV, IRR & more",
        rating:"4.5",
        price:529,
        category:"Finance & Accounting",
        subcat:"Finance"
    },
    {
        id:44,
        img:"https://img-c.udemycdn.com/course/480x270/1356742_c0b1_5.jpg",
        heading:"The Complete Personal Finance Course: Save,Protect,Make More",           
        author:"Chris Haroun",
        des:"3 Courses in 1! Save,Protect & Make More! By an Award Winning MBA Professor, VC & Best Selling Online Business Teacher.",
        rating:"4.8",
        price:529,
        category:"Finance & Accounting",
        subcat:"Finance"
    },
    {
        id:45,
        img:"https://img-c.udemycdn.com/course/480x270/1466336_9108_4.jpg",
        heading:"Acorns' Guide to Personal Finance",           
        author:"Jennifer Barrett, Jennifer Barrett",
        des:"5 Steps to Building Wealth: Budget Better, Pay Off Debt Faster, Save and Earn More Money and Invest Wisely",
        rating:"4.4",
        price:5229,
        category:"Finance & Accounting",
        subcat:"Finance"
    },
    {
        id:46,
        img:"https://img-c.udemycdn.com/course/480x270/2105458_c48e_3.jpg",
        heading:"Tax Preparation and Law 2023, 2022, 2021, 2020, & 2019",           
        author:"Robert (Bob) Steele",
        des:"Unlock Tax Filing Confidence with Practical Examples & Step-by-Step Instructions in this Comprehensive Income Tax Course",
        rating:"4.3",
        price:529,
        category:"Finance & Accounting",
        subcat:"Taxes"
    },
    {
        id:47,
        img:"https://img-c.udemycdn.com/course/480x270/2280894_3022_2.jpg",
        heading:"Fundamentals of Business Taxes",           
        author:"Mike M.",
        des:"Learn the fundamentals of business taxes and understand the basics of doing taxes for your business",
        rating:"4.6",
        price:529,
        category:"Finance & Accounting",
        subcat:"Taxes"
    },
    {
        id:48,
        img:"https://img-c.udemycdn.com/course/480x270/724596_2500_7.jpg",
        heading:"Tax Preparation: Learn Fast! Prepare Taxes with Confidence!",           
        author:"Stefan Ignatovski, Ph.D.",
        des:"Become a confident tax preparer by learning about taxes and applications over practical examples and scenarios.",
        rating:"4.1",
        price:529,
        category:"Finance & Accounting",
        subcat:"Taxes"
    },
    {
        id:49,
        img:"https://img-c.udemycdn.com/course/480x270/354336_ff6f_10.jpg",
        heading:"US Income Taxes - Income Tax Preparation Simplified for You",           
        author:"Majo Jacinto",
        des:"The A - Z of self-preparing and e-filing your basic income taxes by 04/15. Income tax preparation made easy for you.",
        rating:"4.8",
        price:529,
        category:"Finance & Accounting",
        subcat:"Taxes"
    },
    {
        id:50,
        img:"https://img-c.udemycdn.com/course/480x270/1172716_e612.jpg",
        heading:"Personal Income Tax in Canada",           
        author:"Debi Peverill",
        des:"Good Stuff to Know",
        rating:"4.4",
        price:529,
        category:"Finance & Accounting",
        subcat:"Taxes"
    },
    {
        id:51,
        img:"https://img-c.udemycdn.com/course/480x270/2196488_8fc7_10.jpg",
        heading:"Ultimate AWS Certified Solutions Architect Associate SAA-C03",           
        author:"Stephane Maarek",
        des:"Full Practice Exam | Learn Cloud Computing | Pass the AWS Certified Solutions Architect Associate Certification SAA-C03!",
        rating:"4.7",
        price:529,
        category:"IT & Software",
        subcat:"IT Certification"
    },
    {
        id:52,
        img:"https://img-c.udemycdn.com/course/480x270/3142166_a637_3.jpg",
        heading:"[NEW] Ultimate AWS Certified Cloud Practitioner CLF-C02",           
        author:"Stephane Maarek",
        des:"Full Practice Exam included + explanations | Learn Cloud Computing | Pass the AWS Cloud Practitioner CLF-C02 exam!",
        rating:"4.7",
        price:529,
        category:"IT & Software",
        subcat:"IT Certification"
    },
    {
        id:53,
        img:"https://img-c.udemycdn.com/course/480x270/2394982_eaac_8.jpg",
        heading:"AZ-900: Microsoft Azure Fundamentals Exam Prep - OCT 2023",           
        author:"Scott Duffy",
        des:"Learn the fundamentals of Azure, and get certified, with this complete beginner's AZ-900 course, includes practice test!",
        rating:"4.6",
        price:529,
        category:"IT & Software",
        subcat:"IT Certification"
    },
    {
        id:54,
        img:"https://img-c.udemycdn.com/course/480x270/2015076_2944_7.jpg",
        heading:"CompTIA Security+ (SY0-701) Complete Course & Exam",           
        author:"Jason Dion",
        des:"CompTIA Security+ (SY0-701) Bootcamp - Your preparation for the world's best cybersecurity certification!",
        rating:"4.8",
        price:649,
        category:"IT & Software",
        subcat:"IT Certification"
    },
    {
        id:55,
        img:"https://img-c.udemycdn.com/course/480x270/2301254_26c8_6.jpg",
        heading:"Certified Kubernetes Administrator (CKA) with Practice Tests",           
        author:"Mumshad Mannambeth",
        des:"Prepare for the Certified Kubernetes Administrators Certification with live practice tests right in your browser - CKA",
        rating:"4.7",
        price:529,
        category:"IT & Software",
        subcat:"IT Certification"
    },
    {
        id:56,
        img:"https://img-c.udemycdn.com/course/480x270/857010_8239_2.jpg",
        heading:"Learn Ethical Hacking From Scratch",           
        author:"Zaid Sabih",
        des:"Become an ethical hacker that can hack like black hat hackers and secure systems like cybersecurity experts",
        rating:"4.6",
        price:529,
        category:"IT & Software",
        subcat:"Network & Security"
    },
    {
        id:57,
        img:"https://img-c.udemycdn.com/course/480x270/1602900_f550_10.jpg",
        heading:"Kubernetes for the Absolute Beginners - Hands-on",           
        author:"Mumshad Mannambeth",
        des:"Learn Kubernetes in simple, easy and fun way with hands-on coding exercises. For beginners in DevOps.",
        rating:"4.7",
        price:529,
        category:"IT & Software",
        subcat:"Network & Security"
    },
    {
        id:58,
        img:"https://img-c.udemycdn.com/course/480x270/614772_233b_9.jpg",
        heading:"The Complete Cyber Security Course : Hackers Exposed!",           
        author:"Nathan House",
        des:"Volume 1 : Become a Cyber Security Specialist, Learn How to Stop Hackers, Prevent Hacking,  Learn IT Security &  INFOSEC",
        rating:"4.5",
        price:529,
        category:"IT & Software",
        subcat:"Network & Security"
    },
    {
        id:59,
        img:"https://img-c.udemycdn.com/course/480x270/1236568_5ada_11.jpg",
        heading:"The Absolute Beginners Guide to Cyber Security 2023 - Part 1",           
        author:"Alexander Oni",
        des:"Learn Cyber Security concepts such as hacking, malware, firewalls, worms, phishing, encryption, biometrics, BYOD & more",
        rating:"4.6",
        price:529,
        category:"IT & Software",
        subcat:"Network & Security"
    },
    {
        id:60,
        img:"https://img-c.udemycdn.com/course/480x270/437490_c76a_4.jpg",
        heading:"The Complete Ethical Hacking Course: Beginner to Advanced!",           
        author:"Ermin Kreponic",
        des:"Learn how to do ethical hacking, penetration testing, web testing, and wifi hacking using kali linux!",
        rating:"4.3",
        price:529,
        category:"IT & Software",
        subcat:"Network & Security"
    },
    {
        id:61,
        img:"https://img-c.udemycdn.com/course/480x270/118042_251a_13.jpg",
        heading:"PLC Fundamentals (Level I)",           
        author:"Paul Lynn",
        des:"This course will give a person with no prior experience the basic tools necessary to create a PLC program from scratch.",
        rating:"4.7",
        price:529,
        category:"IT & Software",
        subcat:"Hardware"
    },
    {
        id:62,
        img:"https://img-c.udemycdn.com/course/480x270/2068149_a63b_9.jpg",
        heading:"Microcontroller Embedded C Programming: Absolute Beginners",           
        author:"Kiran Nayak",
        des:"Foundation course on Embedded C programming  using STM32 Microcontroller.",
        rating:"4.6",
        price:529,
        category:"IT & Software",
        subcat:"Hardware"
    },
    {
        id:63,
        img:"https://img-c.udemycdn.com/course/480x270/643206_2ee7_9.jpg",
        heading:"Mastering Microcontroller and Embedded Driver Development",           
        author:"Kiran Nayak",
        des:"(MCU1) Learn bare metal driver development using Embedded C: Writing drivers for STM32 GPIO,I2C,SPI,USART  from scratch",
        rating:"4.6",
        price:529,
        category:"IT & Software",
        subcat:"Hardware"
    },
    {
        id:64,
        img:"https://img-c.udemycdn.com/course/480x270/982708_2483_2.jpg",
        heading:"Arduino Step by Step: Getting Started",           
        author:"Dr. Peter Dalmaris",
        des:"The original comprehensive course designed for new Arduino Makers",
        rating:"4.6",
        price:529,
        category:"IT & Software",
        subcat:"Hardware"
    },
    {
        id:65,
        img:"https://img-c.udemycdn.com/course/480x270/2828052_b461_2.jpg",
        heading:"5G: Technologies, Architecture And Protocols",           
        author:"Dr. Moazzam Tiwana",
        des:"5G Air Interface Channels, Voice Over 5G, Security in 5G, NG-RAN, 5G Core, 5G Explained according to 3GPP specifications",
        rating:"4.4",
        price:529,
        category:"IT & Software",
        subcat:"Hardware"
    },
    {
        id:66,
        img:"https://img-c.udemycdn.com/course/480x270/256758_e35d_5.jpg",
        heading:"Learn Linux in 5 Days and Level Up Your Career",           
        author:"Jason Cannon",
        des:"Use the in-demand Linux skills you learn in this course to get promoted or start a new career as a Linux professional.",
        rating:"4.6",
        price:529,
        category:"IT & Software",
        subcat:"Operating system & Servers"
    },
    {
        id:67,
        img:"https://img-c.udemycdn.com/course/480x270/95246_69f4_23.jpg",
        heading:"Linux Command Line Basics",           
        author:"Ahmed Alkabary, Bandar Alghaleb",
        des:"This is an introductory course to the Linux command Line. It's great for both Linux beginners and advanced Linux users.",
        rating:"4.6",
        price:529,
        category:"IT & Software",
        subcat:"Operating system & Servers"
    },
    {
        id:68,
        img:"https://img-c.udemycdn.com/course/480x270/924090_507a_3.jpg",
        heading:"Linux Administration Bootcamp: Go from Beginner to Advanced",           
        author:"Jason Cannon",
        des:"Learn Red Hat Linux & CentOS: Use the in-demand skills to start a career as a Linux Server Admin or Linux Administrator!",
        rating:"4.5",
        price:529,
        category:"IT & Software",
        subcat:"Operating system & Servers"
    },
    {
        id:69,
        img:"https://img-c.udemycdn.com/course/480x270/1349660_ecfb_4.jpg",
        heading:"Linux Shell Scripting: A Project-Based Approach to Learning",           
        author:"Jason Cannon",
        des:"Learn how to shell script through project-based training (Bash Scripting, Bash Programming, Sed, Grep, Awk, and More)",
        rating:"4.5",
        price:529,
        category:"IT & Software",
        subcat:"Operating system & Servers"
    },
    {
        id:70,
        img:"https://img-c.udemycdn.com/course/480x270/2767896_eb29_5.jpg",
        heading:"Mastering Data Modeling Fundamentals",           
        author:"Alan Simon",
        des:"Entity-Relationship Techniques and Best Practices",
        rating:"4.4",
        price:529,
        category:"IT & Software",
        subcat:"Operating system & Servers"
    },
    {
        id:71,
        img:"https://img-c.udemycdn.com/course/480x270/1332278_4ea6_5.jpg",
        heading:"Docker for the Absolute Beginner - Hands On - DevOps",           
        author:"Mumshad Mannambeth",
        des:"Learn Docker with Hands On Coding Exercises. For beginners in DevOps",
        rating:"4.6",
        price:629,
        category:"IT & Software",
        subcat:"Other IT & Software"
    },
    {
        id:72,
        img:"https://img-c.udemycdn.com/course/480x270/1151036_64b6_6.jpg",
        heading:"Blockchain and Bitcoin Fundamentals",           
        author:"George Levy",
        des:"Learn the key elements of blockchain and Bitcoin in this bestselling video course and accompanying PDF glossary.",
        rating:"4.6",
        price:529,
        category:"IT & Software",
        subcat:"Other IT & Software"
    },
    {
        id:73,
        img:"https://img-c.udemycdn.com/course/480x270/1209412_842c_7.jpg",
        heading:"Ansible for the Absolute Beginner - Hands-On - DevOps",           
        author:"Mumshad Mannambeth",
        des:"This course introduces Ansible to the absolute beginner in DevOps. Practice Ansible with coding exercises in browser.",
        rating:"4.5",
        price:529,
        category:"IT & Software",
        subcat:"Other IT & Software"
    },
    {
        id:74,
        img:"https://img-c.udemycdn.com/course/480x270/2604078_8780.jpg",
        heading:"Google Cloud Platform (GCP) Fundamentals for Beginners",           
        author:"Janakiram MSV",
        des:"Learn How to Use Key GCP Services From the Ground Up Through Hands-On Demos and Detailed Use Cases!",
        rating:"4.5",
        price:529,
        category:"IT & Software",
        subcat:"Other IT & Software"
    },
    {
        id:75,
        img:"https://img-c.udemycdn.com/course/480x270/5117770_4ac9_5.jpg",
        heading:"How to use ChatGPT and Generative AI to help create content",           
        author:"Justin B",
        des:"Master the art of language AI: Learn to generate high-quality content, automate tasks, and unleash your creativity.",
        rating:"4.5",
        price:599,
        category:"IT & Software",
        subcat:"Other IT & Software"
    },
    {
        id:76,
        img:"https://img-c.udemycdn.com/course/480x270/355212_948a_10.jpg",
        heading:"Wordpress for Beginners - Master Wordpress Quickly",           
        author:"Andrew Williams",
        des:"In 2023, build a beautiful responsive Wordpress site that looks great on all devices.  No experience required.",
        rating:"4.6",
        price:529,
        category:"Design",
        subcat:"Web Design"
    },
    {
        id:77,
        img:"https://img-c.udemycdn.com/course/480x270/3227583_5e75_6.jpg",
        heading:"Complete Web & Mobile Designer in 2023: UI/UX, Figma, +more",           
        author:"Andrei Neagoie",
        des:"Become a Designer in 2023! Master Mobile and Web Design, User Interface + User Experience (UI/UX Design), HTML, and CSS",
        rating:"4.5",
        price:529,
        category:"Design",
        subcat:"Web Design"
    },
    {
        id:78,
        img:"https://img-c.udemycdn.com/course/480x270/1561458_7f3b_2.jpg",
        heading:"CSS - The Complete Guide 2023 (incl. Flexbox, Grid & Sass)",           
        author:"Maximilian Schwarzmüller",
        des:"Learn CSS for the first time or brush up your CSS skills and dive in even deeper. EVERY web developer has to know CSS.",
        rating:"4.7",
        price:529,
        category:"Design",
        subcat:"Web Design"
    },
    {
        id:79,
        img:"https://img-c.udemycdn.com/course/480x270/2094300_ebf0_9.jpg",
        heading:"Complete Web Design: from Figma to Webflow to Freelancing",           
        author:"Vako Shvili",
        des:"3 in 1 Course: Learn to design websites with Figma, build with Webflow, and make a living freelancing.",
        rating:"4.8",
        price:529,
        category:"Design",
        subcat:"Web Design"
    },
    {
        id:80,
        img:"https://img-c.udemycdn.com/course/480x270/957940_4115_4.jpg",
        heading:"Learn Photoshop, Web Design & Profitable Freelancing 2023",           
        author:"Cristian Doru Barin",
        des:"Learn Adobe Photoshop and use it to create amazing website designs and create a high, stable income. No coding needed!",
        rating:"4.6",
        price:529,
        category:"Design",
        subcat:"Web Design"
    },
    {
        id:81,
        img:"https://img-c.udemycdn.com/course/480x270/526534_04bb_4.jpg",
        heading:"The Game Design and AI Master Class Beginner to Expert",           
        author:"[ School of Game Design ]",
        des:"3D game design, 2D game design, AI art, VR/AR/XR, Unity, coding, C#, game development, animation, programming, Photoshop",
        rating:"4.2",
        price:529,
        category:"Design",
        subcat:"Game Design"
    },
    {
        id:82,
        img:"https://img-c.udemycdn.com/course/480x270/1772094_5669_4.jpg",
        heading:"Pixel Art Master Course - Beginner to Professional/Freelance",           
        author:"Mislav Majdandžić",
        des:"Learn ALL about pixel art in an always growing course! Get access to basic and pro techniques with daily feedbacks!",
        rating:"4.7",
        price:529,
        category:"Design",
        subcat:"Game Design"
    },
    {
        id:83,
        img:"https://img-c.udemycdn.com/course/480x270/65306_a9c7_5.jpg",
        heading:"Adobe Illustrator: Mastering the Fundamentals",           
        author:"[ School of Game Design ]",
        des:"Learn powerful illustration techniques in Adobe Illustrator master digital painting and graphic design with new skills!",
        rating:"4.4",
        price:529,
        category:"Design",
        subcat:"Game Design"
    },
    {
        id:84,
        img:"https://img-c.udemycdn.com/course/480x270/397936_513f_3.jpg",
        heading:"Pixel art for Video games",           
        author:"Marco Vale",
        des:"The essential course for creating stunning pixel art graphics for video-games or stylish illustrations and designs",
        rating:"4.5",
        price:529,
        category:"Design",
        subcat:"Game Design"
    },
    {
        id:85,
        img:"https://img-c.udemycdn.com/course/480x270/1318732_86ee_3.jpg",
        heading:"Visual Effects for Games in Unity - Beginner To Intermediate",           
        author:"Gabriel Aguiar",
        des:"By the end of this course you will have started your own portfolio as a Triple-A Visual Effects artist for Games.",
        rating:"4.6",
        price:529,
        category:"Design",
        subcat:"Game Design"
    },
    {
        id:86,
        img:"https://img-c.udemycdn.com/course/480x270/438522_500f_7.jpg",
        heading:"Complete Blender Creator: Learn 3D Modelling for Beginners",           
        author:"GameDev",
        des:"Use Blender to Create Beautiful 3D models for Video Games, 3D Printing & More. Beginners Level Course",
        rating:"4.7",
        price:529,
        category:"Design",
        subcat:"3D & Animation"
    },
    {
        id:87,
        img:"https://img-c.udemycdn.com/course/480x270/627730_83d0_41.jpg",
        heading:"The Complete Adobe After Effects Bootcamp: Basic to Advanced",           
        author:"Louay Zambarakji",
        des:"Learn Adobe After Effects CC:  Master Motion Graphics, VFX Visual Effects & VFX Compositing - 50+ Real World Project",
        rating:"4.7",
        price:529,
        category:"Design",
        subcat:"3D & Animation"
    },
    {
        id:88,
        img:"https://img-c.udemycdn.com/course/480x270/683198_ef78_8.jpg",
        heading:"Creating 3D environments in Blender",           
        author:"Rob Tuytel",
        des:"Learn Blender 3.2, explore Geometry Nodes and create wonderful 3D environments",
        rating:"4.8",
        price:529,
        category:"Design",
        subcat:"3D & Animation"
    },
    {
        id:89,
        img:"https://img-c.udemycdn.com/course/480x270/551930_3c01_2.jpg",
        heading:"SOLIDWORKS: Become a Certified Associate Today (CSWA)",           
        author:"Tayseer Almattar",
        des:"SolidWorks Training: Learn to Master SolidWorks to the Associate Certification Level Even if You are a Complete Beginner",
        rating:"4.6",
        price:529,
        category:"Design",
        subcat:"3D & Animation"
    },
    {
        id:90,
        img:"https://img-c.udemycdn.com/course/480x270/1329786_8aa9_7.jpg",
        heading:"After Effects - Motion Graphics & Data Visualization",           
        author:"Daniel Walter Scott",
        des:"Using Adobe After Effects create beautiful VFX Visual Effects, data visualization & VFX Compositing.",
        rating:"4.7",
        price:529,
        category:"Design",
        subcat:"3D & Animation"
    },
    {
        id:91,
        img:"ttps://img-c.udemycdn.com/course/480x270/3205406_f076_4.jpg",
        heading:"Clo3D for beginners",           
        author:"Lena Merrin",
        des:"This course will teach you how to create 3D garments in CLO",
        rating:"4.5",
        price:529,
        category:"Design",
        subcat:"Fashion Design"
    },
    {
        id:92,
        img:"https://img-c.udemycdn.com/course/480x270/2284600_278b_7.jpg",
        heading:"Sketching for Fashion Design ~ Beginner Course for Designers",           
        author:"Nino Via",
        des:"Learn Step-by-Step Professional Fashion Drawing Techniques. Using Croquis, Plumb Lines, Body Movement, Shading, Folds et",
        rating:"4.3",
        price:529,
        category:"Design",
        subcat:"Fashion Design"
    },
    {
        id:93,
        img:"https://img-c.udemycdn.com/course/480x270/2200350_37d8_4.jpg",
        heading:"Pattern Making for Fashion Design -PART 1- Essential Skills!",           
        author:"Nino Via",
        des:"How to Use Pattern Making Principals and Techniques to Draft and Manipulate Patterns to Create Your Fashion Design Ideas",
        rating:"4.5",
        price:529,
        category:"Design",
        subcat:"Fashion Design"
    },
    {
        id:94,
        img:"https://img-c.udemycdn.com/course/480x270/1768758_aaeb_6.jpg",
        heading:"How To Create A Fashion Collection and Launch Your Own Brand",           
        author:"Nino Via",
        des:"Designing a Fashion Line. A step-by-step Comprehensive Guide for Mastering Fashion Designing: from Inspiration to Market",
        rating:"4.6",
        price:529,
        category:"Design",
        subcat:"Fashion Design"
    },
    {
        id:95,
        img:"https://img-c.udemycdn.com/course/480x270/453832_2597_5.jpg",
        heading:"Pattern Cutting & Making for Absolute Beginners - Fashion ",           
        author:"Caroline Barulis",
        des:"The ultimate video series for learning basic pattern cutting/making. WE DON'T COVER BLOCK CREATION",
        rating:"4.5",
        price:529,
        category:"Design",
        subcat:"Fashion Design"
    },
    {
        id:96,
        img:"https://img-c.udemycdn.com/course/480x270/914296_3670_8.jpg",
        heading:"The Complete Digital Marketing Course - 12 Courses in 1",           
        author:"Rob Percival",
        des:"Master Digital Marketing Strategy, Social Media Marketing, SEO, YouTube, Email, Facebook Marketing, Analytics & More!",
        rating:"4.5",
        price:529,
        category:"Marketing",
        subcat:"Digital Marketing"
    },
    {
        id:97,
        img:"https://img-c.udemycdn.com/course/480x270/1659676_128a_19.jpg",
        heading:"The Complete Digital Marketing Guide - 24 Courses in 1",           
        author:"Robin & Jesper",
        des:"Digital Marketing & Social Media, ChatGPT, Prompt Engineering, Google Ads, Facebook, SEO, WordPress, Instagram, YouTube.",
        rating:"4.6",
        price:529,
        category:"Marketing",
        subcat:"Digital Marketing"
    },
    {
        id:98,
        img:"https://img-c.udemycdn.com/course/480x270/1931752_1012_15.jpg",
        heading:"Mega Digital Marketing Course A-Z: 12 Courses in 1 + Updates",           
        author:"Pouya Eti • Digital Marketing Expert",
        des:"Digital Marketing Strategy, Social Media Marketing, WordPress, SEO, ChatGPT, Email, Instagram, Facebook, YouTube, ads",
        rating:"4.6",
        price:529,
        category:"Marketing",
        subcat:"Digital Marketing"
    },
    {
        id:99,
        img:"https://img-c.udemycdn.com/course/480x270/2344164_6fb8_10.jpg",
        heading:"Social Media Marketing Agency : Digital Marketing + Business",           
        author:"Pouya Eti • Digital Marketing Expert",
        des:"Learn to build a business, find clients, & social media marketing all in one. Facebook ads, Instagram, Google ads & ...",
        rating:"4.5",
        price:529,
        category:"Marketing",
        subcat:"Digital Marketing"
    },
    {
        id:100,
        img:"https://img-c.udemycdn.com/course/480x270/2524202_0720_16.jpg",
        heading:"Digital Marketing Agency | Start a Social Media Business",           
        author:"Robin & Jesper",
        des:"Build a Digital Marketing Agency Business with Social Media (SMMA), ChatGPT, Facebook Ads, Instagram, WordPress, SEO",
        rating:"4.7",
        price:529,
        category:"Marketing",
        subcat:"Digital Marketing"
    },
    {
        id:101,
        img:"https://img-c.udemycdn.com/course/480x270/484606_5721_16.jpg",
        heading:"Instagram Marketing: Complete Guide To Instagram Growth",           
        author:"Benjamin Wilson, Entrepreneur Academy",
        des:"Attract Hyper-Targeted Instagram Followers, Convert Followers to Paying Customers, & Expand your Brand Using Instagram",
        rating:"4.4",
        price:529,
        category:"Marketing",
        subcat:"Social Media Marketing"
    },
    {
        id:102,
        img:"https://img-c.udemycdn.com/course/480x270/403314_b091_3.jpg",
        heading:"Facebook Ads & Facebook Marketing MASTERY 2023 | Coursenvy ®",           
        author:"COURSE ENVY",
        des:"Facebook Marketing from beginner to advanced! Join 200,000+ students who MASTERED Facebook and are Facebook Ads experts!",
        rating:"4.6",
        price:529,
        category:"Marketing",
        subcat:"Social Media Marketing"
    },
    {
        id:103,
        img:"https://img-c.udemycdn.com/course/480x270/573984_ce2a_3.jpg",
        heading:"Social Media Marketing MASTERY 2023 | Ads on 10+ Platforms",           
        author:"COURSE ENVY",
        des:"MASTER online marketing on Meta, Pinterest, Instagram, YouTube, Facebook, Google and more ad platforms! Coursenvy",
        rating:"4.4",
        price:529,
        category:"Marketing",
        subcat:"Social Media Marketing"
    },
    {
        id:104,
        img:"https://img-c.udemycdn.com/course/480x270/450394_b942_8.jpg",
        heading:"Social Media Marketing - Complete Certificate Course",           
        author:"SO ME Academy",
        des:"The comprehensive social media course, beginner to advanced. Go viral, get started today!",
        rating:"4.7",
        price:529,
        category:"Marketing",
        subcat:"Social Media Marketing"
    },
    {
        id:105,
        img:"https://img-c.udemycdn.com/course/480x270/1692684_682b.jpg",
        heading:"Instagram Marketing 2023: Hashtags, Live, Stories, Ads &more",           
        author:"Evan Kimbrell",
        des:"Watch me take an account from an idea to 40k followers in 4 months. 14 hours instruction, 8 hours of BTS videos",
        rating:"4.6",
        price:529,
        category:"Marketing",
        subcat:"Social Media Marketing"
    },
    {
        id:106,
        img:"https://img-c.udemycdn.com/course/480x270/2356538_211e_2.jpg",
        heading:"The Ultimate Public Relations Masterclass",           
        author:"Heather Baker",
        des:"Everything you need to know to be successful at PR in a digital world",
        rating:"4.6",
        price:529,
        category:"Marketing",
        subcat:"Public Relationship"
    },
    {
        id:107,
        img:"https://img-c.udemycdn.com/course/480x270/285332_421c_7.jpg",
        heading:"Public Relations: Media Crisis Communications",           
        author:"TJ Walker",
        des:"Public Relations: You Can Shape and Control Your Media Messages at The Worst Possible Times",
        rating:"4.5",
        price:529,
        category:"Marketing",
        subcat:"Public Relationship"
    },
    {
        id:108,
        img:"https://img-c.udemycdn.com/course/480x270/689296_dd18_3.jpg",
        heading:"Modern PR: How To Get Press Coverage For Your Business",           
        author:"Brad Merrill",
        des:"A proven public relations / PR system to get press coverage for your company or product, from a journalist's perspective",
        rating:"4.6",
        price:529,
        category:"Marketing",
        subcat:"Public Relationship"
    },
    {
        id:109,
        img:"https://img-c.udemycdn.com/course/480x270/363882_1582_3.jpg",
        heading:"Presentation Skills: Give a Great New Business Pitch",           
        author:"TJ Walker",
        des:"Presentation skills - You can make your prospects understand and remember your unique  value proposiiton",
        rating:"4.5",
        price:529,
        category:"Marketing",
        subcat:"Public Relationship"
    },
    {
        id:110,
        img:"https://img-c.udemycdn.com/course/480x270/208456_3337_10.jpg",
        heading:"Press Coverage, Publicity & Public Relations For Branding",           
        author:"Alex Genadinik",
        des:"Public relations to reach 100,000+ people with influencer marketing, publicity, and press coverage for personal branding",
        rating:"4.4",
        price:529,
        category:"Marketing",
        subcat:"Public Relationship"
    },
    {
        id:111,
        img:"https://img-c.udemycdn.com/course/480x270/325666_fe45_3.jpg",
        heading:"Copywriting secrets - How to write copy that sells",           
        author:"Sean Kaye",
        des:"Discover the secrets of copywriting success from the master. From novice to pro in easy stages",
        rating:"4.5",
        price:529,
        category:"Marketing",
        subcat:"Content Marketing"
    },
    {
        id:112,
        img:"https://img-c.udemycdn.com/course/480x270/176138_463f_15.jpg",
        heading:"Business Writing & Technical Writing Immersion",           
        author:"Starweaver Instructor Team, Paul Siegel",
        des:"Effective Writing | Technical Documentation | Writing System | Software Documentation | Emails | PPTs",
        rating:"4.5",
        price:529,
        category:"Marketing",
        subcat:"Content Marketing"
    },
    {
        id:113,
        img:"https://img-c.udemycdn.com/course/480x270/1331661_87ad_2.jpg",
        heading:"Writing Tools & Hacks: Copywriting/Blogging/Content Writing",           
        author:"Tyler Speegle",
        des:"The best FREE writing tools & apps + Hacks to take your copywriting, blogging, & content writing to the next level.",
        rating:"4.2",
        price:529,
        category:"Marketing",
        subcat:"Content Marketing"
    },
    {
        id:114,
        img:"https://img-c.udemycdn.com/course/480x270/1667390_68bd_5.jpg",
        heading:"Content Marketing Masterclass: Create Content That Sells",           
        author:"Brad Merrill",
        des:"Master content marketing to grow your business: content creation, promotion, copywriting, SEO, email marketing, & more!",
        rating:"4.5",
        price:529,
        category:"Marketing",
        subcat:"Content Marketing"
    },
    {
        id:115,
        img:"https://img-c.udemycdn.com/course/480x270/835336_5dc5_12.jpg",
        heading:"Blogging for a Living -  Perfect Small Budget Project",           
        author:"Theo McArthur",
        des:"Make a full-time living or much more. In depth step-by-step blogging blueprint. Evergreen, beginner friendly, and fun!",
        rating:"4.5",
        price:529,
        category:"Marketing",
        subcat:"Content Marketing"
    },
    {
        id:116,
        img:"https://img-c.udemycdn.com/course/480x270/1045092_8c2f_2.jpg",
        heading:"The Art & Science of Drawing / BASIC SKILLS",           
        author:"Brent Eviston",
        des:"Drawing is not a talent. It's a skill anyone can learn.",
        rating:"4.8",
        price:529,
        category:"Life Style",
        subcat:"Arts & Crafts"
    },
    {
        id:117,
        img:"https://img-c.udemycdn.com/course/480x270/2234122_68c5_8.jpg",
        heading:"How to Draw From Beginner to Master",           
        author:"Joseph Patric Daniels",
        des:"Drawing and Shading From Fundamentals to Photorealism",
        rating:"4.7",
        price:529,
        category:"Life Style",
        subcat:"Arts & Crafts"
    },
    {
        id:118,
        img:"https://img-c.udemycdn.com/course/480x270/3285798_8312_4.jpg",
        heading:"Watercolor Painting For Beginners | By Award Winning Artist",           
        author:"Broderick Wong",
        des:"Learn the Essentials | Master the Basics | Two full workshops packed in 1 great course | All the FUN without the FLUFF!",
        rating:"4.6",
        price:529,
        category:"Life Style",
        subcat:"Arts & Crafts"
    },
    {
        id:119,
        img:"https://img-c.udemycdn.com/course/480x270/635090_4503.jpg",
        heading:"How To Make Soap - Homemade Soap Making for Beginners",           
        author:"Shona O'Connor, Howorama Inc.",
        des:"How to make your own soap at home using the cold process soapmaking method. A step by step guide for beginners",
        rating:"4.4",
        price:529,
        category:"Life Style",
        subcat:"Arts & Crafts"
    },
    {
        id:120,
        img:"https://img-c.udemycdn.com/course/480x270/137230_76b8_2.jpg",
        heading:"The Secrets to Drawing",           
        author:"Matthew Fussell",
        des:"A comprehensive video and ebook course designed for people wanting to learn the core concepts of drawing.",
        rating:"4.5",
        price:529,
        category:"Life Style",
        subcat:"Arts & Crafts"
    },
    {
        id:121,
        img:"https://img-c.udemycdn.com/course/480x270/3193072_2d3c_2.jpg",
        heading:"Makeup Artistry Basic to Masterclass , Online Makeup Course",           
        author:"Hajar Beauty Academy",
        des:"Daily make up and evening makeup on different skin tones, eye shapes & face shape, online makeup courses , Makeup artist",
        rating:"4.5",
        price:529,
        category:"Life Style",
        subcat:"Beauty & Makeup"
    },
    {
        id:122,
        img:"https://img-c.udemycdn.com/course/480x270/1465170_295f.jpg",
        heading:"Natural Beauty: How to Make Lotions, Creams and Body Butters",           
        author:"Jennifer Schroeder",
        des:"How to create your own natural skincare lotions harnessing the power of healing plants for natural beauty and wellness",
        rating:"4.8",
        price:529,
        category:"Life Style",
        subcat:"Beauty & Makeup"
    },
    {
        id:123,
        img:"https://img-c.udemycdn.com/course/480x270/2651938_83dc_2.jpg",
        heading:"Diploma in Luxury Facial, Facial Machines, Chemical Peeling",           
        author:"Institute Of Beauty Secrets",
        des:"CPDLearning Basic & Advanced techniques in facials with 5 stars client satisfaction everytime and achieve facial results",
        rating:"4.6",
        price:529,
        category:"Life Style",
        subcat:"Beauty & Makeup"
    },
    {
        id:124,
        img:"https://img-c.udemycdn.com/course/480x270/2549721_b29c.jpg",
        heading:"Eyebrow Microblading Full course UPDATED",           
        author:"Kristina Wood",
        des:"From A to Z steps of performing eyebrow microblading treatment, accredited certificate possibility",
        rating:"4.5",
        price:529,
        category:"Life Style",
        subcat:"Beauty & Makeup"
    },
    {
        id:125,
        img:"https://img-c.udemycdn.com/course/480x270/541690_c67a_8.jpg",
        heading:"Natural Skincare :: Luscious herbal Recipes for Younger Skin",           
        author:"Elizabeth Heck",
        des:"Easily make superior & safe skin care using natural herbs and botanicals from herbalism. Beauty at its best!",
        rating:"4.5",
        price:529,
        category:"Life Style",
        subcat:"Beauty & Makeup"
    },
    {
        id:126,
        img:"https://img-c.udemycdn.com/course/480x270/587486_d25f_4.jpg",
        heading:"#1 Sourdough Bread Baking 101",           
        author:"Teresa L Greenway",
        des:"Bake your first real sourdough bread with coaching from an expert sourdough bread baker.",
        rating:"4.7",
        price:529,
        category:"Life Style",
        subcat:"Food & Beverage"
    },
    {
        id:127,
        img:"https://img-c.udemycdn.com/course/480x270/1113854_d302_2.jpg",
        heading:"Essential Cooking Skills",           
        author:"Viorel Copolovici",
        des:"Cook like a pro, master the basic techniques used in the World's culinary industry! Key Techniques - Part 1",
        rating:"4.5",
        price:529,
        category:"Life Style",
        subcat:"Food & Beverage"
    },
    {
        id:128,
        img:"https://img-c.udemycdn.com/course/480x270/863126_a899_5.jpg",
        heading:"Healthy Cooking Fundamentals",           
        author:"Chef Nic DeMuth",
        des:"A practical course to take your cooking skills from dull to delicious",
        rating:"4.7",
        price:529,
        category:"Life Style",
        subcat:"Food & Beverage"
    },
    {
        id:129,
        img:"https://img-c.udemycdn.com/course/480x270/383612_5575_5.jpg",
        heading:"#2 Bake Artisan Sourdough Bread Like a Professional",           
        author:"Teresa L Greenway",
        des:"Baking the best bread means baking real Sourdough Bread. NO KNEAD bread -  video baking classes in your own home.",
        rating:"4.5",
        price:529,
        category:"Life Style",
        subcat:"Food & Beverage"
    },
    {
        id:130,
        img:"https://img-c.udemycdn.com/course/480x270/1215282_fcc3.jpg",
        heading:"Perfect French Macarons #1 - Simple to Sensational",           
        author:"Cake Nuvo",
        des:"Master the art of baking amazing macaron cookies consistently, and create stunning macaron towers and plated desserts",
        rating:"4.8",
        price:529,
        category:"Life Style",
        subcat:"Food & Beverage"
    },
    {
        id:131,
        img:"https://img-c.udemycdn.com/course/480x270/320482_89ab_6.jpg",
        heading:"Dog CPR, First Aid + Safety for pet pros + dedicated owners",           
        author:"Melanie Monteiro",
        des:"Essential training to keep your dogs safe, attract clients & gain skills & confidence to take action in an emergency.",
        rating:"4.8",
        price:529,
        category:"Life Style",
        subcat:"Pet Care & Training"
    },
    {
        id:132,
        img:"https://img-c.udemycdn.com/course/480x270/626182_207f_2.jpg",
        heading:"Simple Solutions for Common Dog Behavior & Training Problems",           
        author:"Ian Dunbar",
        des:"Learn to address house soiling, chewing, barking, digging, separation anxiety, jumping up, pulling on leash and more",
        rating:"4.7",
        price:529,
        category:"Life Style",
        subcat:"Pet Care & Training"
    },
    {
        id:133,
        img:"https://img-c.udemycdn.com/course/480x270/1177482_cafc.jpg",
        heading:"Inside Your Dog's Mind with Victoria Stilwell",           
        author:"Victoria Stilwell",
        des:"Understanding canine behavior and how dogs think, feel and learn to make dog training easier & more effective.",
        rating:"4.7",
        price:529,
        category:"Life Style",
        subcat:"Pet Care & Training"
    },
    {
        id:134,
        img:"https://img-c.udemycdn.com/course/480x270/53424_d671_8.jpg",
        heading:"Dr. Ian Dunbar's SIRIUS® Dog Trainer Academy - All 4 Days",           
        author:"Ian Dunbar",
        des:"Learn how to train dogs the SIRIUS® way!  Learn how to run and promote your own dog-friendly dog training business.",
        rating:"4.8",
        price:529,
        category:"Life Style",
        subcat:"Pet Care & Training"
    },
    {
        id:135,
        img:"https://img-c.udemycdn.com/course/480x270/52115_7cf9_7.jpg",
        heading:"Science-Based Dog Training (with Feeling) - All 3 Days",           
        author:"Ian Dunbar",
        des:"Learn effective and enjoyable dog training methods that are science-based and ready for real-world dog training.",
        rating:"4.7",
        price:529,
        category:"Life Style",
        subcat:"Pet Care & Training"
    },
    {
        id:136,
        img:"https://img-c.udemycdn.com/course/480x270/1392122_6c4c_3.jpg",
        heading:"iPhone Photography | Take Professional Photos On Your iPhone",           
        author:"Dale McManus",
        des:"Your Online Guide to Taking Stunning iPhone Photography Like a Professional Digital Photographer",
        rating:"4.5",
        price:529,
        category:"Photography & Video",
        subcat:"Digital Photography"
    },
    {
        id:137,
        img:"https://img-c.udemycdn.com/course/480x270/138374_4359_5.jpg",
        heading:"Beginner Nikon Digital SLR (DSLR) Photography",           
        author:"JP Teaches Photo",
        des:"Learn how to use your camera intuitively. Learn through doing rather than memorizing.",
        rating:"4.7",
        price:529,
        category:"Photography & Video",
        subcat:"Digital Photography"
    },
    {
        id:138,
        img:"https://img-c.udemycdn.com/course/480x270/387536_ca0e_5.jpg",
        heading:"Digital Photography for Beginners with DSLR cameras",           
        author:"Villiers Steyn",
        des:"Learn how to take stunning photographs by mastering both the technical and creative sides of digital photography.",
        rating:"4.7",
        price:529,
        category:"Photography & Video",
        subcat:"Digital Photography"
    },
    {
        id:139,
        img:"https://img-c.udemycdn.com/course/480x270/1145580_bfd0_10.jpg",
        heading:"GIMP 2.10 Masterclass: From Beginner to Pro Photo Editing",           
        author:"Michael Davies",
        des:"GIMP 2.10 Complete Guide - Learn the Free Photo Editor GIMP. Go From a Beginner to Pro in Photo Editing & Graphic Design",
        rating:"4.6",
        price:529,
        category:"Photography & Video",
        subcat:"Digital Photography"
    },
    {
        id:140,
        img:"https://img-c.udemycdn.com/course/480x270/291860_7947_3.jpg",
        heading:"Beginner Canon Digital SLR (DSLR) Photography",           
        author:"JP Teaches Photo",
        des:"Learn how to use your camera intuitively. Learn through doing rather than memorizing.",
        rating:"4.5",
        price:529,
        category:"Photography & Video",
        subcat:"Digital Photography"
    },
    {
        id:141,
        img:"https://img-c.udemycdn.com/course/480x270/1462428_639f_8.jpg",
        heading:"Photography Masterclass: A Complete Guide to Photography",           
        author:"Phil Ebiner",
        des:"The Best Online Professional Photography Class: How to Take Amazing Photos for Beginners & Advanced Photographers",
        rating:"4.8",
        price:529,
        category:"Photography & Video",
        subcat:"Photography"
    },
    {
        id:142,
        img:"https://img-c.udemycdn.com/course/480x270/1213796_b6c8_4.jpg",
        heading:"Photography Fundamentals for Beginners: 1-Hour Crash Course",           
        author:"Phil Ebiner",
        des:"A Quick Photography Course. Learn aperture, shutter speed, ISO and composition rules in this quick photography course.",
        rating:"4.6",
        price:529,
        category:"Photography & Video",
        subcat:"Photography"
    },
    {
        id:143,
        img:"https://img-c.udemycdn.com/course/480x270/794572_ac1d.jpg",
        heading:"Affinity Photo (version 1) : Solid Foundations",           
        author:"Simon Foster",
        des:"The best selling beginners guide to Affinity Photo - complete with a 50 page PDF to aid your study!",
        rating:"4.7",
        price:529,
        category:"Photography & Video",
        subcat:"Photography"
    },
    {
        id:144,
        img:"https://img-c.udemycdn.com/course/480x270/840622_1ff1_3.jpg",
        heading:"Food Photography: Capturing Food in Your Kitchen",           
        author:"Phil Ebiner",
        des:"With DIY Food Photography, you'll be taking better photos in no time with what you have in your own kitchen!",
        rating:"4.3",
        price:529,
        category:"Photography & Video",
        subcat:"Photography"
    },
    {
        id:145,
        img:"https://img-c.udemycdn.com/course/480x270/1644218_1b3a.jpg",
        heading:"Complete Photography : 21 Courses in 1 [Beginner to Expert]",           
        author:"Creative Online School",
        des:"Learn Portrait Photography, Landscape Photography, Stock Photography, Photography Composition, Black and White, and more",
        rating:"4.5",
        price:529,
        category:"Photography & Video",
        subcat:"Photography"
    },
    {
        id:146,
        img:"https://img-c.udemycdn.com/course/480x270/926512_6fdf_8.jpg",
        heading:"Adobe Premiere Pro CC Masterclass: Video Editing in Premiere",           
        author:"Phil Ebiner",
        des:"Learn Beginner-Advanced Adobe Premiere Pro Video Editing, Audio Editing, Color Grading, Motion Graphics, Green Screen+",
        rating:"4.7",
        price:529,
        category:"Photography & Video",
        subcat:"Video Design"
    },
    {
        id:147,
        img:"https://img-c.udemycdn.com/course/480x270/1390206_97cb_17.jpg",
        heading:"Video Editing in DaVinci Resolve 18/17: Beginner to Advanced",           
        author:"Louay Zambarakji",
        des:"Learn Video Editing in DaVinci Resolve with Color Correction & Color Grading & Visual Effects in DaVinci Resolve 18.5",
        rating:"4.6",
        price:529,
        category:"Photography & Video",
        subcat:"Video Design"
    },
    {
        id:148,
        img:"https://img-c.udemycdn.com/course/480x270/1110904_66f5_8.jpg",
        heading:"Complete Filmmaker Guide: Become an Incredible Video Creator",           
        author:"Julian Melanson",
        des:"(2023 RELAUNCH) Everything from Pre-Production to Video Editing | Cinematography, Video Production & Filmmaking",
        rating:"4.6",
        price:529,
        category:"Photography & Video",
        subcat:"Video Design"
    },
    {
        id:149,
        img:"https://img-c.udemycdn.com/course/480x270/973762_010a_15.jpg",
        heading:"After Effects CC: The Ultimate Motion Graphics Masterclass",           
        author:"Louay Zambarakji",
        des:"Create Motion Graphics with Adobe After Effects CC: Become a Top Motion Graphics Designer in After Effects CC",
        rating:"4.7",
        price:529,
        category:"Photography & Video",
        subcat:"Video Design"
    },
    {
        id:150,
        img:"https://img-c.udemycdn.com/course/480x270/640808_ca84_3.jpg",
        heading:"Cinematography Masterclass: Videography + Cinematography",           
        author:"Phil Ebiner",
        des:"Cinematography Masterclass: Video Production, Video Lighting, Filmmaking on Any Camera. Improve Your Cinematography",
        rating:"4.5",
        price:529,
        category:"Photography & Video",
        subcat:"Video Design"
    },
    {
        id:151,
        img:"https://img-c.udemycdn.com/course/480x270/142490_7eb7_5.jpg",
        heading:"Mastering Architecture and Real Estate Photography",           
        author:"Charlie Borland",
        des:"Start a business photographing real estate photography jobs for architects, builders, and real estate agents",
        rating:"4.4",
        price:529,
        category:"Photography & Video",
        subcat:"Commercial Photography"
    },
    {
        id:152,
        img:"https://img-c.udemycdn.com/course/480x270/557386_009f_5.jpg",
        heading:"Wedding Photography: Complete Guide to Wedding Photography",           
        author:"Phil Ebiner",
        des:"Learn exactly how to become a wedding photographer, start a photo business of your own, and shoot better wedding photos.",
        rating:"4.5",
        price:529,
        category:"Photography & Video",
        subcat:"Commercial Photography"
    },
    {
        id:153,
        img:"https://img-c.udemycdn.com/course/480x270/119486_87e4_11.jpg",
        heading:"Basic Food Photography",           
        author:"Andrew Olson",
        des:"Learn how to take delicious food photos from scratch",
        rating:"4.4",
        price:529,
        category:"Photography & Video",
        subcat:"Commercial Photography"
    },
    {
        id:154,
        img:"https://img-c.udemycdn.com/course/480x270/1416588_17ec_2.jpg",
        heading:"Real Estate Photography: How To Get Started",           
        author:"Greg Gottfried",
        des:"Discover the secrets to starting a highly profitable real estate photo business. Taking Photos, Editing, Delivery etc.",
        rating:"4.8",
        price:529,
        category:"Photography & Video",
        subcat:"Commercial Photography"
    },
    {
        id:155,
        img:"https://img-c.udemycdn.com/course/480x270/2400178_b478_2.jpg",
        heading:"Start Your Photography Business: A Photography Course",           
        author:"Phil Ebiner",
        des:"A step-by-step guide to launching your own successful photography business!",
        rating:"4.6",
        price:529,
        category:"Photography & Video",
        subcat:"Commercial Photography"
    },
    {
        id:156,
        img:"https://img-c.udemycdn.com/course/480x270/238934_4d81_7.jpg",
        heading:"Pianoforall - Incredible New Way To Learn Piano & Keyboard",           
        author:"Robin Hall",
        des:"Learn Piano in WEEKS not years. Play-By-Ear & learn to Read Music. Pop, Blues, Jazz, Ballads, Improvisation, Classical",
        rating:"4.7",
        price:529,
        category:"Music & Arts",
        subcat:"Instruments"
    },
    {
        id:157,
        img:"https://img-c.udemycdn.com/course/480x270/42271_886a_9.jpg",
        heading:"Complete Guitar Lessons System - Beginner to Advanced",           
        author:"Erich Andreas",
        des:"All-in-one Guitar Course, Fingerstyle Guitar, Blues Guitar, Acoustic Guitar, Electric Guitar & Fingerpicking Guitarra",
        rating:"4.6",
        price:529,
        category:"Music & Arts",
        subcat:"Instruments"
    },
    {
        id:158,
        img:"https://img-c.udemycdn.com/course/480x270/1132342_48ec_3.jpg",
        heading:"Ultimate Beginner Guitar Masterclass",           
        author:"Henry Olsen",
        des:"Beginner Guitar Lessons: Learn Acoustic Guitar, Blues Guitar, Basic Fingerstyle Guitar, Guitar Chords, Guitar Technique",
        rating:"4.8",
        price:529,
        category:"Music & Arts",
        subcat:"Instruments"
    },
    {
        id:159,
        img:"https://img-c.udemycdn.com/course/480x270/200598_16d5_11.jpg",
        heading:"Learn to play HARMONICA, the easiest instrument to pick up!",           
        author:"Ben Hewlett",
        des:"Ultimate diatonic harmonica lessons, blues, country music, rock; you will learn how to play on/off stage, solo/group",
        rating:"4.7",
        price:529,
        category:"Music & Arts",
        subcat:"Instruments"
    },
    {
        id:160,
        img:"https://img-c.udemycdn.com/course/480x270/456284_80ce_9.jpg",
        heading:"The Professional Guitar Masterclass",           
        author:"Michael Palmisano",
        des:"Learn The Tools Used By The World's Top Professional Guitar Players.",
        rating:"4.2",
        price:7900,
        category:"Music & Arts",
        subcat:"Instruments"
    },
    {
        id:161,
        img:"https://img-c.udemycdn.com/course/480x270/826876_4fd1_6.jpg",
        heading:"Music + Audio Production in Logic Pro X - The Complete Guide",           
        author:"Make Pro Music",
        des:"Become a master at using Logic Pro X | Understand music production | Learn to record, edit & mix audio to a pro standard",
        rating:"4.5",
        price:529,
        category:"Music & Arts",
        subcat:"Music Production"
    },
    {
        id:162,
        img:"https://img-c.udemycdn.com/course/480x270/897192_2cee_12.jpg",
        heading:"Music Production in Logic Pro X - The Complete Course!",           
        author:"Tomas George",
        des:"Join Successful Music Production + Logic Pro X students in Creating, Recording, Mixing Music + Mastering in Logic Pro X",
        rating:"4.8",
        price:529,
        category:"Music & Arts",
        subcat:"Music Production"
    },
    {
        id:163,
        img:"https://img-c.udemycdn.com/course/480x270/1435772_8edb_6.jpg",
        heading:"Music Production in Ableton Live 10 - The Complete Course!",           
        author:"Tomas George, Digital Music Masters",
        des:"Learn Music Production in Ableton Live 10 Today and Understand how to Create, Record and Edit Your Own Music + Live Sets",
        rating:"4.8",
        price:529,
        category:"Music & Arts",
        subcat:"Music Production"
    },
    {
        id:164,
        img:"https://img-c.udemycdn.com/course/480x270/953366_6d67.jpg",
        heading:"Game Music Composition: Make Music For Games From Scratch",           
        author:"Karleen Heong",
        des:"Learn to compose music for any and every type of video game, from complete beginner to competent game music composer",
        rating:"4.5",
        price:529,
        category:"Music & Arts",
        subcat:"Music Production"
    },
    {
        id:165,
        img:"https://img-c.udemycdn.com/course/480x270/1962026_c87e_5.jpg",
        heading:"FL Studio - Music Production + Mixing Music -Complete Course",           
        author:"Tomas George",
        des:"Learn Music Production in FL Studio for Mac + PC for Recording, Editing, Composing, Mixing and Mastering in FL Studio",
        rating:"4.6",
        price:529,
        category:"Music & Arts",
        subcat:"Music Production"
    },
    {
        id:166,
        img:"https://img-c.udemycdn.com/course/480x270/1250174_48d9_14.jpg",
        heading:"BECOME A GREAT SINGER: Your Complete Vocal Training System",           
        author:"Robert Lunte",
        des:"Immediately Improve Your Singing. (Any Level, Any Style)",
        rating:"4.4",
        price:529,
        category:"Music & Arts",
        subcat:"Vocal"
    },
    {
        id:167,
        img:"https://img-c.udemycdn.com/course/480x270/1516474_7722.jpg",
        heading:"SINGING SIMPLIFIED #1: The Fast-Track to Singing Like a Pro",           
        author:"Steve Glazer",
        des:"Find your unique voice naturally, while having FUN doing it!  A modern approach to singing lessons & vocal training.",
        rating:"4.7",
        price:529,
        category:"Music & Arts",
        subcat:"Vocal"
    },
    {
        id:168,
        img:"https://img-c.udemycdn.com/course/480x270/70030_c4e7_8.jpg",
        heading:"Elite Singing Techniques - Phase I",           
        author:"Eric Arceneaux",
        des:"Step by step singing system proven to develop great technique and vocal mastery, Results are immediate!",
        rating:"4.9",
        price:3399,
        category:"Music & Arts",
        subcat:"Vocal"
    },
    {
        id:169,
        img:"https://img-c.udemycdn.com/course/480x270/211024_a2df_2.jpg",
        heading:"Be a Voice Actor: Making a Living with Your Voice",           
        author:"Laci Morgan",
        des:"Learn the tools and techniques to get started in the world of voiceovers",
        rating:"4.4",
        price:799,
        category:"Music & Arts",
        subcat:"Vocal"
    },
    {
        id:170,
        img:"https://img-c.udemycdn.com/course/480x270/2180630_9c9b_3.jpg",
        heading:"Breathing Bootcamp for Singers",           
        author:"Eric Arceneaux",
        des:"Sing With Power, Beauty, and Control!",
        rating:"4.9",
        price:529,
        category:"Music & Arts",
        subcat:"Vocal"
    },
    {
        id:171,
        img:"https://img-c.udemycdn.com/course/480x270/2018498_268a.jpg",
        heading:"FL Studio 21 - Music Production In FL Studio 21 for Mac & PC",           
        author:"Martin Svensson, Music-Prod Education",
        des:"Electronic Music Production in FL Studio 21 - 6 Full Tracks: Music Recording, Audio Editing, EQ & Mastering FL Studio 21",
        rating:"4.4",
        price:699,
        category:"Music & Arts",
        subcat:"Music Software"
    },
    {
        id:172,
        img:"https://img-c.udemycdn.com/course/480x270/1592962_53fb_3.jpg",
        heading:"Ultimate Ableton Live 10 COMPLETE: Parts 1, 2, and 3",           
        author:"Jason Allen",
        des:"Learning Ableton Live 10 Suite through tutorials, tracks, and more. Learn the Live software download quickly and easily!",
        rating:"4.4",
        price:799,
        category:"Music & Arts",
        subcat:"Music Software"
    },
    {
        id:173,
        img:"https://img-c.udemycdn.com/course/480x270/3968950_7120_6.jpg",
        heading:"Ableton Certified Training: Ableton Live 11 (Part 1, 2, & 3)",           
        author:"Jason Allen",
        des:"Official Parts 1, 2, and 3 from Ableton Certified Training Curriculum and Training J. Anthony Allen",
        rating:"4.6",
        price:699,
        category:"Music & Arts",
        subcat:"Music Software"
    },
    {
        id:174,
        img:"https://img-c.udemycdn.com/course/480x270/1576666_d19b_3.jpg",
        heading:"Adobe Audition CC: The Beginner's Guide to Adobe Audition",           
        author:"Video School",
        des:"Learn how to record, edit and mix audio in Adobe Audition CC with these easy-to-follow audio editing tutorials.",
        rating:"4.3",
        price:699,
        category:"Music & Arts",
        subcat:"Music Software"
    },
    {
        id:175,
        img:"https://img-c.udemycdn.com/course/480x270/1633746_c2c0.jpg",
        heading:"Logic Pro X 101 Masterclass - Logic Pro Music Production",           
        author:"Martin Svensson, Music-Prod Education",
        des:"Learn How To Create 10 Full Tracks With Logic Pro X From Scratch in This Logic Pro X Masterclass, Project Files Included",
        rating:"4.6",
        price:699,
        category:"Music & Arts",
        subcat:"Music Software"
    },
    {
        id:176,
        img:"",
        heading:"",           
        author:"",
        des:"",
        rating:"4.8",
        price:529,
        category:"",
        subcat:""
    },
]